# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abf93324787426cabebc213ab5c6bfd65b4bde7ec564f91d1fc2227037bf78fb3cb6a1630e5fe7fb819ef84c32b57bcda5e0938e181ed65f7c36535aec0dd253

test:
  secret_key_base: cc0087e0cf87e85570e11e181ddae48a49f80c4a5db39a4d13c2eae9fb3e8bcdef2e46235ba2425c4d512d0b9cd1a9857605f0d3d6d06861bbf4114ed2ebe62a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
